### ISSUE TITLE
Email address validation rejects valid addresses with apostrophe character

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/virtualhome#201]
Hi,

I've just run into this when trying to create an account for a real person....

When creating new accounts, email addresses with an apostrophe (single-quote) character ````'```` get rejected even though they are valid addresses:

````
Error

The account could not be validated, check errors
Oops, there were some errors

    Property [email] of class [class aaf.vhr.ManagedSubject] with value [john.o’connor@resistance.mil] is not a valid e-mail address
````

The ````aaf.vhr.ManagedSubject```` domain class used email address validation constraint on the email address field: 

````
  static constraints = {
  ....
  email blank:false, unique:true, email:true
  ....
  }
````

According to [Grails documentation](https://grails.github.io/grails-doc/2.2.3/ref/Constraints/email.html), email address validation is done via [org.apache.commons.validator.EmailValidator](http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/EmailValidator.html) (now deprecated in favour of [org.apache.commons.validator.routines.EmailValidator](http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/EmailValidator.html) ).

But I have no idea how to tweak it to permit the ````'```` character...

Any ideas?

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Apologies, please discard the issue.

Works all fine.

I got tricked by pasting from an email and having the true single-quote (````'````) replaced by a typographic unicode representation of the apostrophe...

False alarm - sorry about the confusion.

Cheers,
Vlad

**Comment by smangelsdorf** [comment]
Thanks for the update.
