### ISSUE TITLE
Captcha Style

### ISSUE THREAD

**Issue by toomaj** [ausaccessfed/virtualhome#202]
It's better if all reCaptcha elements can fit into the right DOM!
I tried to achieve that with adding css "height: 20px;" and  "line-height: normal;" properties to ".recaptchatable #recaptcha_response_field {}", then the input height will not be overridden. 
 
![image](https://cloud.githubusercontent.com/assets/7086960/10440816/d946a890-7185-11e5-82ba-4e0c90411582.png)

![fixed](https://cloud.githubusercontent.com/assets/7086960/10440936/da1d57b8-7186-11e5-8170-1318f823f279.jpg)

**Comment by smangelsdorf** [comment]
We can address this while simultaneously moving to [the new v2 reCAPTCHA](https://www.google.com/recaptcha/api2/demo) in VH3.
