### ISSUE TITLE
NPE when CAPTCHA is required but not provided

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/virtualhome#222]
Hi @bradleybeddoes ,
We have run into issues (reported by end-users) when:
* A user enters incorrect credentials multiple times and gets above the threshold for requiring CAPTCHA
* The user then starts a new session, and enters credentials on the login page (not asking for CAPTCHA).
* Login service then fails with a NPE, resulting into a 500 Internal Server Error.

The stack trace points to 
https://github.com/ausaccessfed/virtualhome/blob/develop/virtualhome/grails-app/services/aaf/vhr/LoginService.groovy#L58
The recaptcha plugin (version 1.2.0) does not verify if params contain `g-recaptcha-response` and just blindly get the value, resulting into an NPE:
https://github.com/iamthechad/grails-recaptcha/blob/4fd02e0233aa3c55ca23b0aeed62109023370571/grails-app/services/com/megatome/grails/RecaptchaService.groovy#L147

This is a known issue in the plugin:
https://github.com/iamthechad/grails-recaptcha/issues/48
and has already been fixed:
https://github.com/iamthechad/grails-recaptcha/commit/92a817d15c2d3a092b372135cc78bd8928f52ce6

However, version 1.7.0 of the plugin, which would provide the fix, would require Grails 2.4.

That would be a major change of the VHO code-base - so as an interim workaround I have a fix:

```
diff --git a/virtualhome/grails-app/services/aaf/vhr/LoginService.groovy b/virtualhome/grails-app/services/aaf/vhr/Login
index a43f72b..823bdce 100644
--- a/virtualhome/grails-app/services/aaf/vhr/LoginService.groovy
+++ b/virtualhome/grails-app/services/aaf/vhr/LoginService.groovy
@@ -44,6 +44,10 @@ class LoginService implements InitializingBean{
     loginCache.getIfPresent(sessionID)
   }

+  private boolean recaptchaResponsePresent(params) {
+    return params["g-recaptcha-response"] != null
+  }
+
   public boolean passwordLogin(ManagedSubject managedSubjectInstance, String password, def request, def session, def pa
     if(!managedSubjectInstance.canLogin()) {
       String reason = "User attempted login but account is disabled."
@@ -55,7 +59,7 @@ class LoginService implements InitializingBean{
       return false
     }

-    if( managedSubjectInstance.requiresLoginCaptcha() && !recaptchaService.verifyAnswer(session, request.getRemoteAddr(
+    if( managedSubjectInstance.requiresLoginCaptcha() && (!recaptchaResponsePresent(params) || !recaptchaService.verify
       String reason = "User provided invalid captcha data."
       String requestDetails = createRequestDetails(request)

```

What are your overall thoughts on this?  And would you welcome a PR with the above patch?

Thanks a lot in advance for getting back to me.

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
PR for this workaround would be great, thanks.
